# Generated by Django 3.0.8 on 2021-11-15 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0005_auto_20200712_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='language',
            field=models.CharField(choices=[('Vietnamese', 'Vietnamese'), ('English', 'English')], default='Vietnamese', max_length=20),
        ),
    ]
